" Gui Configuration
if has("gui_running")
  colorscheme vividchalk
  set number
  set guifont=Menlo:h14
  set guioptions=egmrLt
end

filetype plugin indent on  " Automatically detect file types.
let mapleader = ","
syntax enable

set autoindent
set autowrite  " Writes on make/shell commands
set backspace=start,indent
set clipboard=unnamed
set expandtab
set cursorline
set formatoptions=tcqr
set hidden
set history=256  " Number of things to remember in history.
set hlsearch
set ignorecase
set laststatus=2  " Always show status line.
set modifiable
set nocompatible  " We don't want vi compatibility.
set nocp incsearch
set noerrorbells  " No noise.
set novisualbell  " No blinking .
set pastetoggle=<F6>
set ruler  " Ruler on
set smartcase
set smarttab
set sw=2
set timeoutlen=200  " Time to wait after ESC (default causes an annoying delay)
set ts=2
set wildmode=longest,list

" Shortcuts
cab Q quit
cab W write
cab Wq wq
map ,c :cd %:p:h<CR>
map ,s :w !psql gilt_us_development \| less<CR>
map ,x :bwipeout!<CR>
nmap <expr> <Leader>e ':e ' . expand('%:p:h')
"
" " Stops the cursor reaching the bottom of the screen which is a god send
" " because when you're writing huge functions you end up typing on the bottom
" " line else and you can't see how much space you have.
set scrolloff=3

" Trailing Whitespace Highlighting
highlight ExtraWhitespace ctermbg=red guibg=red
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhitespace /\s\+$/

" FuzzyFinder
let g:fuf_file_exclude = '\v\~$|\.(o|exe|dll|bak|swp|class|tar|gz)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])'
nnoremap <Leader>f     :FufFile **/<CR>
