set nocompatible  " We don't want vi compatibility.
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle "tpope/vim-fugitive"
Bundle "tpope/vim-rails"
Bundle "tpope/vim-fugitive"
Bundle "tpope/vim-fugitive"
Bundle  "Raimondi/delimitMate"
Bundle  "kchmck/vim-coffee-script.git"
Bundle  "pangloss/vim-javascript"
Bundle  "tpope/vim-fugitive.git"
Bundle  "tpope/vim-haml.git"
Bundle  "tpope/vim-rails.git"
Bundle  "tpope/vim-repeat.git"
Bundle  "tpope/vim-surround.git"
Bundle  "Lokaltog/vim-powerline"
Bundle  "briancollins/vim-jst.git"
Bundle  "kien/ctrlp.vim.git"
Bundle  "myusuf3/numbers.vim.git"
Bundle  "scrooloose/syntastic.git"
Bundle  "slim-template/vim-slim.git"
Bundle  "sickill/vim-pasta.git"
Bundle  "tpope/vim-bundler.git"
Bundle  "tpope/vim-endwise.git"

syntax on
filetype plugin indent on  " Automatically detect file types.

" Gui Configuration
if has("gui_running")
  set number
  set background=dark
  set guifont=Inconsolata:h14
  set guioptions=egmrLt
end

runtime macros/matchit.vim

let mapleader = ";"
let maplocalleader = ";"
set autoindent
set autowrite  " Writes on make/shell commands
set backspace=start,indent
set clipboard=unnamed
set expandtab
set formatoptions=tcqr
set hidden
set history=256  " Number of things to remember in history.
set listchars=tab:▸\ ,trail:¬   " UTF-8 characters for trailing whitespace
set hlsearch
set ignorecase
set laststatus=2  " Always show status line.
set modifiable
set nocp incsearch
set noerrorbells  " No noise.
set novisualbell  " No blinking .
set ruler  " Ruler on
set scrolloff=3
set smartcase
set smarttab
set timeoutlen=200  " Time to wait after ESC (default causes an annoying delay)
set wildmode=longest,list
set tabstop=2
set shiftwidth=2
set softtabstop=2
set wildignore+=*.o,*.obj,.git,*.pdf,*.gif,*.png,*.jpg,*.ico
scriptencoding utf-8


" Shortcuts
map <Leader>s :w<CR>
cab Q quit
cab W write
cab Wq wq
nmap <expr> <Leader>e ':e ' . expand('%:p:h')

" Syntastic
let g:ruby_path = "/Users/rdeshpande/.rvm/rubies/default/bin"

nnoremap <Leader>f     :CtrlPMRUFiles<CR>
let g:ctrlp_custom_ignore = {
      \ 'dir':  '\.git$\|\.hg$\|\.svn$',
      \ 'file': '\.exe$\|\.so$\|\.dll$' }

" Vim-pasta
let g:pasta_enabled_filetypes = ['ruby', 'javascript', 'css', 'sh']

" Consider question/exclamation marks to be part of a Vim word.
autocmd FileType ruby set iskeyword=@,48-57,_,?,!,192-255
autocmd FileType scss set iskeyword=@,48-57,_,-,?,!,192-255
au BufNewFile,BufRead *.ejs set filetype=jst

let g:ragtag_global_maps = 1 
let g:Powerline_symbols = 'fancy'
let g:neocomplcache_enable_at_startup = 1
